spring:
  application:
    name: eureka_server

server:
  port: 8761


eureka:
  client:
#    不注册自己
    register-with-eureka: false
#    不拉区服务列表
    fetch-registry: false

  server:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #    关闭自我保护：剔除没有心跳反应的节点
    enable-self-preservation: false