#---------------------------------------------------------------------------------
server:
  port: 8761
#---------------------------------------------------------------------------------

eureka:
#  instance:
#    hostname: peer2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #注册到eureka
    register-with-eureka: false
  server:
     # 关闭自我保护
    enable-self-preservation: false
    # 清除服务的时间
    eviction-interval-timer-in-ms: 10000
#---------------------------------------------------------------------------------
spring:
  application:
    name: eureka-server
